coverage:
  status:
    project:
      default:
        threshold: 90%
    patch:
      default:
        threshold: 90%
ignore:
  - "lua/colorbox/commons/*.lua"
  - "lua/colorbox/commons/**/*.lua"
  - "lua/colorbox/commons/**/**/*.lua"
